framework:
    esi: { enabled: true }
    translator: { fallbacks: [en] }
    secret: '%secret%'
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        #save_path: '/var/lib/php/mycache'
        cookie_lifetime: 18000
        gc_maxlifetime: 18000
    fragments: ~
    http_method_override: true
    #disallow_search_engine_index: false


    php_errors:
        log: true
    #secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.

    #esi: true
    #fragments: true

    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        prefix_seed: impulsetravel.co

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        #app: cache.adapter.system
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu
