doctrine:
    orm:
        metadata_cache_driver: apcu
        query_cache_driver: apcu

services:
    doctrine.system_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.system_cache_pool'

framework:
    cache:
        pools:
            doctrine.system_cache_pool:
                adapter: cache.system
